// SPDX-License-Identifier: LGPL-2.1-or-later

/***************************************************************************
 *   Copyright (c) 2026 FreeCAD project contributors                       *
 *                                                                         *
 *   This file is part of the FreeCAD CAx development system.              *
 *                                                                         *
 *   This library is free software; you can redistribute it and/or         *
 *   modify it under the terms of the GNU Library General Public           *
 *   License as published by the Free Software Foundation; either          *
 *   version 2 of the License, or (at your option) any later version.      *
 *                                                                         *
 *   This library  is distributed in the hope that it will be useful,      *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU Library General Public License for more details.                  *
 *                                                                         *
 *   You should have received a copy of the GNU Library General Public     *
 *   License along with this library; see the file COPYING.LIB. If not,    *
 *   write to the Free Software Foundation, Inc., 59 Temple Place,         *
 *   Suite 330, Boston, MA  02111-1307, USA                                *
 *                                                                         *
 ***************************************************************************/

#pragma once

#include <cstddef>
#include <string_view>

/* Tokenizer for the FreeCAD expression language.
 *
 * This is a handwritten, constexpr replacement for the former flex lexer
 * (Expression.l).  Tokenization is purely lexical: word-like tokens are
 * reported as NAME regardless of whether they name a unit, a document
 * object, or a property - that decision belongs to the parser, which
 * interprets names according to their context.
 *
 * Token kind values and names are kept compatible with the ones the old
 * bison-generated parser exposed, because tokenize() consumers compare
 * against them.  NAME is an alias of IDENTIFIER; the UNIT kind is only
 * produced for the symbol units (degree sign, prime, double prime) that
 * are not word-shaped, and USUNIT for the quote characters.
 */

namespace App::ExpressionParser
{

enum TokenKind : int
{
    // Values 1..255 are the corresponding literal characters.
    FUNC = 258,
    ONE,   // produced by refineOne(), never by nextToken()
    NUM,
    IDENTIFIER,
    UNIT,
    USUNIT,
    INTEGER,
    CONSTANT,
    CELLADDRESS,
    EQ,
    NEQ,
    LT,
    GT,
    GTE,
    LTE,
    STRING,
    MINUSSIGN,
    NAME = IDENTIFIER,
    END = 0,
};

struct LexToken
{
    int kind {END};
    std::size_t start {0};
    std::size_t len {0};

    constexpr bool operator==(const LexToken&) const = default;
};

namespace Lexer
{

constexpr bool isDigit(char c)
{
    return '0' <= c && c <= '9';
}

constexpr bool isAsciiAlpha(char c)
{
    return ('a' <= c && c <= 'z') || ('A' <= c && c <= 'Z');
}

/// Multi-byte tokens with a fixed UTF-8 spelling.
constexpr std::string_view utf8Minus = "\xe2\x88\x92";        // U+2212 MINUS SIGN
constexpr std::string_view utf8Degree = "\xc2\xb0";           // U+00B0 DEGREE SIGN
constexpr std::string_view utf8AngMinute = "\xe2\x80\xb2";    // U+2032 PRIME
constexpr std::string_view utf8AngSecond = "\xe2\x80\xb3";    // U+2033 DOUBLE PRIME

constexpr bool startsWith(std::string_view s, std::size_t pos, std::string_view what)
{
    return s.substr(pos, what.size()) == what;
}

/// Does a non-ASCII sequence at pos spell one of the standalone symbol
/// tokens (which therefore must not be swallowed into a name)?
constexpr bool isSymbolSequence(std::string_view s, std::size_t pos)
{
    return startsWith(s, pos, utf8Minus) || startsWith(s, pos, utf8Degree)
        || startsWith(s, pos, utf8AngMinute) || startsWith(s, pos, utf8AngSecond);
}

/* The flex lexer restricted identifiers to Unicode letter/mark/number
 * categories via generated byte-range tables.  Here any non-ASCII,
 * non-symbol sequence is accepted as part of a name; inputs that only
 * differ in previously-rejected codepoints now fail at evaluation
 * instead of tokenization. */
constexpr bool isNameStart(std::string_view s, std::size_t pos)
{
    const char c = s[pos];
    return isAsciiAlpha(c) || c == '_'
        || (static_cast<unsigned char>(c) >= 0x80 && !isSymbolSequence(s, pos));
}

constexpr bool isNameCont(std::string_view s, std::size_t pos)
{
    const char c = s[pos];
    return isNameStart(s, pos) || isDigit(c) || c == '@';
}

/// Length of a maximal identifier starting at pos, 0 if none.
/// If atFuncPos is non-null, also reports the length of the maximal
/// prefix valid as a function name (no leading '_', no '@').
constexpr std::size_t nameLen(std::string_view s, std::size_t pos, std::size_t* funcNameLen)
{
    if (funcNameLen) {
        *funcNameLen = 0;
    }
    if (pos >= s.size() || !isNameStart(s, pos)) {
        return 0;
    }
    const bool funcOk = s[pos] != '_';
    std::size_t i = pos;
    std::size_t funcEnd = pos;
    while (i < s.size() && isNameCont(s, i)) {
        if (funcOk && funcEnd == i && s[i] != '@') {
            funcEnd = i + 1;
        }
        ++i;
    }
    if (funcNameLen && funcOk) {
        *funcNameLen = funcEnd - pos;
    }
    return i - pos;
}

/// Length of a cell address starting at pos, 0 if none.  The patterns are
/// those of the old lexer: $Letters$Digits, Ll$Digits, $LlDigits (a plain
/// "A1" is an ordinary name; the spreadsheet resolves it by name).
constexpr std::size_t cellLen(std::string_view s, std::size_t pos)
{
    std::size_t best = 0;
    // $[A-Za-z]+${DIGIT}+
    if (pos < s.size() && s[pos] == '$') {
        std::size_t i = pos + 1;
        while (i < s.size() && isAsciiAlpha(s[i])) {
            ++i;
        }
        if (i > pos + 1 && i < s.size() && s[i] == '$') {
            std::size_t j = i + 1;
            while (j < s.size() && isDigit(s[j])) {
                ++j;
            }
            if (j > i + 1) {
                best = j - pos;
            }
        }
        // $[A-Za-z]{1,2}{DIGIT}+
        std::size_t letters = i - (pos + 1);
        if (best == 0 && letters >= 1 && letters <= 2 && i < s.size() && isDigit(s[i])) {
            std::size_t j = i;
            while (j < s.size() && isDigit(s[j])) {
                ++j;
            }
            best = j - pos;
        }
    }
    // [A-Za-z]{1,2}${DIGIT}+
    else {
        std::size_t i = pos;
        while (i < s.size() && isAsciiAlpha(s[i]) && i - pos < 2) {
            ++i;
        }
        if (i > pos && i < s.size() && s[i] == '$') {
            std::size_t j = i + 1;
            while (j < s.size() && isDigit(s[j])) {
                ++j;
            }
            if (j > i + 1) {
                best = j - pos;
            }
        }
    }
    return best;
}

constexpr bool isConstantName(std::string_view name)
{
    return name == "pi" || name == "e" || name == "None" || name == "True" || name == "true"
        || name == "False" || name == "false";
}

/// Length of a numeric literal starting at pos and its kind (NUM or
/// INTEGER), 0 if none.  Faithful to the flex rules including the
/// comma-decimal form: {D}*[.,]{D}+{EXPO}? | {D}+{EXPO} | {D}+
constexpr std::size_t numberLen(std::string_view s, std::size_t pos, int* kind)
{
    std::size_t i = pos;
    while (i < s.size() && isDigit(s[i])) {
        ++i;
    }
    std::size_t intDigits = i - pos;
    std::size_t end = 0;
    if (i < s.size() && (s[i] == '.' || s[i] == ',') && i + 1 < s.size() && isDigit(s[i + 1])) {
        i += 2;
        while (i < s.size() && isDigit(s[i])) {
            ++i;
        }
        end = i;
        *kind = NUM;
    }
    else if (intDigits > 0) {
        end = i;
        *kind = INTEGER;
    }
    else {
        return 0;
    }
    // {EXPO} = [eE][-+]?[0-9]+ ; a bare integer only stays INTEGER
    // without an exponent.
    if (end < s.size() && (s[end] == 'e' || s[end] == 'E')) {
        std::size_t j = end + 1;
        if (j < s.size() && (s[j] == '+' || s[j] == '-')) {
            ++j;
        }
        std::size_t digs = j;
        while (j < s.size() && isDigit(s[j])) {
            ++j;
        }
        if (j > digs) {
            end = j;
            *kind = NUM;
        }
    }
    return end - pos;
}

/// Length of a <<...>> string literal at pos, 0 if unterminated/absent.
/// Contents: backslash-escaped anything, or any char except '\', '>', '\n'.
constexpr std::size_t stringLen(std::string_view s, std::size_t pos)
{
    if (!startsWith(s, pos, "<<")) {
        return 0;
    }
    std::size_t i = pos + 2;
    while (i < s.size()) {
        if (s[i] == '\\') {
            if (i + 1 >= s.size()) {
                return 0;
            }
            i += 2;
        }
        else if (s[i] == '>') {
            if (i + 1 < s.size() && s[i + 1] == '>') {
                return i + 2 - pos;
            }
            return 0;
        }
        else if (s[i] == '\n') {
            return 0;
        }
        else {
            ++i;
        }
    }
    return 0;
}

constexpr bool isSingleCharToken(char c)
{
    // The old lexer's single-character token set.
    return c == '%' || c == '+' || c == '(' || c == ')' || c == '=' || c == '/' || c == '*'
        || c == '^' || c == ',' || c == '.' || c == '{' || c == '}' || c == '[' || c == ']'
        || c == ':' || c == ';' || c == '@' || c == '?' || c == '#';
}

}  // namespace Lexer

/** Scan one token of the expression language starting at pos.
 *
 *  Whitespace is skipped; at end of input a token of kind END is
 *  returned whose start is the input size.  Bytes that match no rule
 *  are returned as their own character token (kind = byte value).
 *
 *  Numeric literals are reported as NUM/INTEGER; use refineOne() with
 *  the parsed value to obtain the historical ONE kind.
 */
constexpr LexToken nextToken(std::string_view s, std::size_t pos)
{
    using namespace Lexer;

    while (pos < s.size() && (s[pos] == ' ' || s[pos] == '\t' || s[pos] == '\n' || s[pos] == '\r')) {
        ++pos;
    }
    if (pos >= s.size()) {
        return {END, s.size(), 0};
    }
    const char c = s[pos];

    // String literal, or two LT tokens when unterminated.
    if (c == '<') {
        if (std::size_t n = stringLen(s, pos)) {
            return {STRING, pos, n};
        }
        if (startsWith(s, pos, "<=")) {
            return {LTE, pos, 2};
        }
        return {LT, pos, 1};
    }
    if (c == '>') {
        if (startsWith(s, pos, ">=")) {
            return {GTE, pos, 2};
        }
        return {GT, pos, 1};
    }
    if (c == '=' && startsWith(s, pos, "==")) {
        return {EQ, pos, 2};
    }
    if (c == '!' && startsWith(s, pos, "!=")) {
        return {NEQ, pos, 2};
    }
    if (c == '-') {
        return {MINUSSIGN, pos, 1};
    }
    if (startsWith(s, pos, utf8Minus)) {
        return {MINUSSIGN, pos, utf8Minus.size()};
    }
    if (startsWith(s, pos, utf8Degree)) {
        return {UNIT, pos, utf8Degree.size()};
    }
    if (startsWith(s, pos, utf8AngMinute)) {
        return {UNIT, pos, utf8AngMinute.size()};
    }
    if (startsWith(s, pos, utf8AngSecond)) {
        return {UNIT, pos, utf8AngSecond.size()};
    }
    if (c == '\'' || c == '"') {
        return {USUNIT, pos, 1};
    }

    // Numbers win over '.'/',' character tokens by longest match.
    {
        int kind = 0;
        if (std::size_t n = numberLen(s, pos, &kind)) {
            return {kind, pos, n};
        }
    }

    // Names, function names, cell addresses, constants.
    {
        std::size_t funcName = 0;
        const std::size_t id = nameLen(s, pos, &funcName);
        std::size_t cell = cellLen(s, pos);
        if (id > 0 || cell > 0) {
            // FUNC: function name, optional tab/DLE filler (a quirk kept
            // from the flex pattern, which used octal \20), then '('.
            if (funcName > 0) {
                std::size_t i = pos + funcName;
                while (i < s.size() && (s[i] == '\t' || s[i] == '\x10')) {
                    ++i;
                }
                if (i < s.size() && s[i] == '(' && i + 1 - pos > id && i + 1 - pos > cell) {
                    return {FUNC, pos, i + 1 - pos};
                }
            }
            if (cell > id) {
                return {CELLADDRESS, pos, cell};
            }
            if (id > 0 && isConstantName(s.substr(pos, id))) {
                return {CONSTANT, pos, id};
            }
            if (id > 0) {
                return {NAME, pos, id};
            }
            return {CELLADDRESS, pos, cell};
        }
    }

    if (isSingleCharToken(c)) {
        return {c, pos, 1};
    }

    // No rule matched: return the byte as a character token.  (The flex
    // lexer's default rule echoed and skipped such bytes instead.)
    return {static_cast<unsigned char>(c), pos, 1};
}

/// The historical lexer reported numeric literals whose value is exactly
/// one as the separate kind ONE.  Value parsing needs the runtime, so the
/// refinement is a separate step.
constexpr int refineOne(int kind, double value)
{
    return (kind == NUM || kind == INTEGER) && value == 1.0 ? ONE : kind;
}

// ---------------------------------------------------------------------
// Compile-time self-tests.

namespace Lexer::SelfTest
{
constexpr int kindAt(std::string_view s, int n)
{
    LexToken t {};
    std::size_t pos = 0;
    for (int i = 0; i <= n; ++i) {
        t = nextToken(s, pos);
        pos = t.start + t.len;
    }
    return t.kind;
}
constexpr std::size_t lenAt(std::string_view s, int n)
{
    LexToken t {};
    std::size_t pos = 0;
    for (int i = 0; i <= n; ++i) {
        t = nextToken(s, pos);
        pos = t.start + t.len;
    }
    return t.len;
}

static_assert(kindAt("mm", 0) == NAME, "unit names lex as generic names");
static_assert(kindAt("foo_bar@baz", 0) == NAME);
static_assert(lenAt("foo_bar@baz", 0) == 11);
static_assert(kindAt("2 mm", 1) == NAME);
static_assert(kindAt("1", 0) == INTEGER, "ONE refinement happens at runtime");
static_assert(kindAt("1.5", 0) == NUM);
static_assert(kindAt("1,5", 0) == NUM, "comma decimals");
static_assert(lenAt("1,5", 0) == 3);
static_assert(kindAt("1, 5", 1) == ',', "comma before space separates");
static_assert(kindAt("1.0e3", 0) == NUM);
static_assert(kindAt("2e3", 0) == NUM);
static_assert(kindAt("pi", 0) == CONSTANT);
static_assert(kindAt("pix", 0) == NAME, "longer name beats constant");
static_assert(kindAt("sqrt(9)", 0) == FUNC);
static_assert(lenAt("sqrt(9)", 0) == 5, "FUNC token includes the paren");
static_assert(kindAt("sqrt (9)", 0) == NAME, "space breaks FUNC, as in flex");
static_assert(kindAt("$A$1", 0) == CELLADDRESS);
static_assert(kindAt("A$1", 0) == CELLADDRESS);
static_assert(kindAt("$A1", 0) == CELLADDRESS);
static_assert(kindAt("A1", 0) == NAME, "plain cell refs are names");
static_assert(kindAt("<<hi>>", 0) == STRING);
static_assert(kindAt("<<a\\>b>>", 0) == STRING);
static_assert(kindAt("<<unterminated", 0) == LT, "broken string decays to LT LT");
static_assert(kindAt("<<unterminated", 1) == LT);
static_assert(kindAt("a <= b", 1) == LTE);
static_assert(kindAt("a == b", 1) == EQ);
static_assert(kindAt("a != b", 1) == NEQ);
static_assert(kindAt("-", 0) == MINUSSIGN);
static_assert(kindAt("\xe2\x88\x92", 0) == MINUSSIGN, "unicode minus");
static_assert(kindAt("\xc2\xb0", 0) == UNIT, "degree symbol");
static_assert(kindAt("5'", 1) == USUNIT);
static_assert(kindAt("a.b", 1) == '.');
static_assert(kindAt(".5", 0) == NUM, "leading-dot decimal");
static_assert(kindAt("", 0) == END);
static_assert(kindAt("  ", 0) == END);
}  // namespace Lexer::SelfTest

}  // namespace App::ExpressionParser
