#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-2.1-or-later
"""Fix a memory bug in the output of bison 3.8's glr2.cc skeleton.

The glr_stack_item copy constructor generated by bison 3.8.x copies the
raw storage of the state/option union with std::memcpy, and the
assignment operator swaps the raw bytes.  Both corrupt non-trivial
semantic value types: a copied std::string in SSO representation keeps
pointing into the source object's buffer, so once the source dies (the
temporary in yynewGLRStackItem, or the old buffer after the state stack
is reallocated in yyexpandGLRStack) the copy reads, writes, or frees
through a dangling pointer.

This script replaces both operations with member-wise copies.  The
yypred/yyfirstVal fields are relative offsets and are copied verbatim so
they survive the block relocation of the state stack; a resolved
semantic value is copy-constructed properly.

Usage: fix-glr2-semantic-copy.py <input> <output>

If the input does not contain the broken pattern (for example a future
bison release fixed it), the file is passed through unchanged.
"""

import sys

COPY_TO_ANCHOR = """\
    /** Type tag for the semantic value.  If true, yyval applies, otherwise
     *  yyfirstVal applies.  */
    bool yyresolved;"""

COPY_TO_METHOD = """\
    /** Copy *this into the uninitialized storage DST.  The yypred and
     *  yyfirstVal fields are copied verbatim: they are relative offsets,
     *  which must survive block relocation of the state stack.  The
     *  semantic value, if resolved, is properly copy-constructed.
     *  (Added by fix-glr2-semantic-copy.py.)  */
    void copy_to (void* dst) const
    {
      glr_state& s = *new (dst) glr_state;
      s.yylrState = yylrState;
      s.yyposn = yyposn;
      s.yypred = yypred;
      if (yyresolved)
        {
          s.yyresolved = true;
          new (&s.value ()) value_type (value ());
        }
      else
        {
          s.yyresolved = false;
          s.yyfirstVal = yyfirstVal;
        }
    }

""" + COPY_TO_ANCHOR

BROKEN_COPY = """\
    glr_stack_item (const glr_stack_item& other) YY_NOEXCEPT YY_NOTHROW
      : is_state_ (other.is_state_)
    {
      std::memcpy (raw_, other.raw_, union_size);
    }

    glr_stack_item& operator= (glr_stack_item other)
    {
      std::swap (is_state_, other.is_state_);
      std::swap (raw_, other.raw_);
      return *this;
    }"""

FIXED_COPY = """\
    // Copy field by field instead of with std::memcpy/byte swaps, which
    // corrupt non-trivial semantic value types (e.g. self-referential
    // SSO strings).  (Modified by fix-glr2-semantic-copy.py.)
    glr_stack_item (const glr_stack_item& other)
      : is_state_ (other.is_state_)
    {
      if (is_state_)
        other.getState ().copy_to (&raw_);
      else
        new (&raw_) semantic_option (other.getOption ());
    }

    glr_stack_item& operator= (const glr_stack_item& other)
    {
      if (this != &other)
        {
          this->~glr_stack_item ();
          new (this) glr_stack_item (other);
        }
      return *this;
    }"""


def main():
    if len(sys.argv) != 3:
        sys.exit(f"usage: {sys.argv[0]} <input> <output>")
    src, dst = sys.argv[1], sys.argv[2]
    with open(src, encoding="utf-8") as f:
        text = f.read()

    if BROKEN_COPY not in text:
        # Assume the skeleton was fixed upstream; pass through unchanged,
        # but fail loudly on a half-recognized file.
        if "std::memcpy (raw_" in text:
            sys.exit(f"{src}: glr_stack_item memcpy found but the expected "
                     "pattern did not match; bison output changed, please "
                     "update fix-glr2-semantic-copy.py")
    else:
        if text.count(COPY_TO_ANCHOR) != 1:
            sys.exit(f"{src}: glr_state anchor not found; bison output "
                     "changed, please update fix-glr2-semantic-copy.py")
        text = text.replace(COPY_TO_ANCHOR, COPY_TO_METHOD)
        text = text.replace(BROKEN_COPY, FIXED_COPY)

    with open(dst, "w", encoding="utf-8") as f:
        f.write(text)


if __name__ == "__main__":
    main()
